export const RICK_MORTY_CHARACTER_LOAD = "RICK_MORTY_CHARACTER_LOAD";
export const RICK_MORTY_CHARACTER_LOAD_FAILURE = "RICK_MORTY_CHARACTER_LOAD_FAILURE";
export const RICK_MORTY_CHARACTER_LOAD_SUCCESS = "RICK_MORTY_CHARACTER_LOAD_SUCCESS";