export const RICK_MORTY_CHARACTER_FAVORITES_ADD =
  "RICK_MORTY_CHARACTER_FAVORITES_ADD";
export const RICK_MORTY_CHARACTER_FAVORITES_ADD_FAILURE =
  "RICK_MORTY_CHARACTER_FAVORITES_ADD_FAILURE";
export const RICK_MORTY_CHARACTER_FAVORITES_ADD_SUCCESS =
  "RICK_MORTY_CHARACTER_FAVORITES_ADD_SUCCESS";
export const RICK_MORTY_CHARACTER_FAVORITES_RESET_ALERT =
  "RICK_MORTY_CHARACTER_FAVORITES_RESET_ALERT";

export const RICK_MORTY_CHARACTER_FAVORITES_LOAD =
  "RICK_MORTY_CHARACTER_FAVORITES_LOAD";
export const RICK_MORTY_CHARACTER_FAVORITES_LOAD_FAILURE =
  "RICK_MORTY_CHARACTER_FAVORITES_LOAD_FAILURE";
export const RICK_MORTY_CHARACTER_FAVORITES_LOAD_SUCCESS =
  "RICK_MORTY_CHARACTER_FAVORITES_LOAD_SUCCESS";
